// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ackley_function
Rcpp::NumericVector ackley_function();
RcppExport SEXP _optimLibR_ackley_function() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ackley_function());
    return rcpp_result_gen;
END_RCPP
}
// logit_optimLib
Rcpp::NumericVector logit_optimLib();
RcppExport SEXP _optimLibR_logit_optimLib() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(logit_optimLib());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optimLibR_ackley_function", (DL_FUNC) &_optimLibR_ackley_function, 0},
    {"_optimLibR_logit_optimLib", (DL_FUNC) &_optimLibR_logit_optimLib, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_optimLibR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
