# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ackley_function <- function() {
    .Call('_optimLibR_ackley_function', PACKAGE = 'optimLibR')
}

#' @export
logit_optimLib <- function() {
    .Call('_optimLibR_logit_optimLib', PACKAGE = 'optimLibR')
}

