# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' logit_optim
#'
#' A simple example optimizing logit regression with optimLib gradient descent
#' @export
ackley_function <- function() {
    .Call(`_optimLibR_ackley_function`)
}

#' logit_optim
#'
#' A simple example optimizing logit regression with optimLib gradient descent
#'
#' @export
logit_optimLib <- function() {
    .Call(`_optimLibR_logit_optimLib`)
}

